### PR TITLE
Fix issue warning message

### PR DESCRIPTION
**Pull request by juliusalberto**
I have:

1. Passes down the `NotificationService` to `CleanupWorker`. I called the notification service directly from the `CleanupWorker` but I'm not sure as I added error formatting in the `CleanupWorker`. Ideally, there will be another method in the `DialogService` class that can take a list of exceptions and print it in the dialog window.
2. Added strings in the `Jabref_en.properties` file

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Comment by Noah-Martin1** [comment]
Why is this failing 4 checks?

**Comment by JxCl-L** [comment]
Looks good to me! Your changes address the issue effectively. Nice work on implementation and updating the necessary files. Yes, the only problem is why some checks not passing. Apart from that, ready for merge in my opinion.

**Comment by juliusalberto** [comment]
> Why is this failing 4 checks?

I think it's because the tests are supposed to be running on the main branch (probably... I'll try running a `./gradlew check` manually and see if it has any unit test failing. Worst case scenario the test will straight up fail when I created a PR to the main branch

**Comment by juliusalberto** [comment]
> Looks good to me! Your changes address the issue effectively. Nice work on implementation and updating the necessary files. Yes, the only problem is why some checks not passing. Apart from that, ready for merge in my opinion.

Do you think I should've put the formatting in the GUI file instead in the logic? The repo maintainer, when I asked about it, specifically said that I should pass down DialogService down to the CleanupWorker. I'm not sure though. Do you think I should just create PR and then wait for their review?

**Comment by juliusalberto** [comment]
Created a new PR to specify which files are changed.

**Pull request closed without merging**
